name: Publish

on:
  release:
    types:
      - published

jobs:
  run-tests:
    name: Run Tests
    uses: oktupol/base-emoji/.github/workflows/test.yml@main

  publish-npmjs:
    name: Publish to npmjs.com
    needs: ['run-tests']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./package-lock.json') }}

      - run: npm ci
      - run: npm pkg set version="${GITHUB_REF_NAME#v}"
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    name: Publish to Github Packages
    needs: ['run-tests']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Cache dependencies
        uses: actions/cache@v6
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./package-lock.json') }}

      - run: npm ci
      - run: npm pkg set version="${GITHUB_REF_NAME#v}"
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}